// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/virtui/v1/virtui.proto

package virtuipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchEventType int32

const (
	WatchEventType_WATCH_EVENT_TYPE_UNSPECIFIED    WatchEventType = 0
	WatchEventType_WATCH_EVENT_TYPE_SCREEN_CHANGED WatchEventType = 1
	WatchEventType_WATCH_EVENT_TYPE_EXITED         WatchEventType = 2
)

// Enum value maps for WatchEventType.
var (
	WatchEventType_name = map[int32]string{
		0: "WATCH_EVENT_TYPE_UNSPECIFIED",
		1: "WATCH_EVENT_TYPE_SCREEN_CHANGED",
		2: "WATCH_EVENT_TYPE_EXITED",
	}
	WatchEventType_value = map[string]int32{
		"WATCH_EVENT_TYPE_UNSPECIFIED":    0,
		"WATCH_EVENT_TYPE_SCREEN_CHANGED": 1,
		"WATCH_EVENT_TYPE_EXITED":         2,
	}
)

func (x WatchEventType) Enum() *WatchEventType {
	p := new(WatchEventType)
	*p = x
	return p
}

func (x WatchEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_virtui_v1_virtui_proto_enumTypes[0].Descriptor()
}

func (WatchEventType) Type() protoreflect.EnumType {
	return &file_proto_virtui_v1_virtui_proto_enumTypes[0]
}

func (x WatchEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchEventType.Descriptor instead.
func (WatchEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{0}
}

type ErrorCategory int32

const (
	ErrorCategory_ERROR_CATEGORY_UNSPECIFIED ErrorCategory = 0
	ErrorCategory_ERROR_CATEGORY_SESSION     ErrorCategory = 1
	ErrorCategory_ERROR_CATEGORY_TERMINAL    ErrorCategory = 2
	ErrorCategory_ERROR_CATEGORY_TIMEOUT     ErrorCategory = 3
	ErrorCategory_ERROR_CATEGORY_VALIDATION  ErrorCategory = 4
	ErrorCategory_ERROR_CATEGORY_DAEMON      ErrorCategory = 5
)

// Enum value maps for ErrorCategory.
var (
	ErrorCategory_name = map[int32]string{
		0: "ERROR_CATEGORY_UNSPECIFIED",
		1: "ERROR_CATEGORY_SESSION",
		2: "ERROR_CATEGORY_TERMINAL",
		3: "ERROR_CATEGORY_TIMEOUT",
		4: "ERROR_CATEGORY_VALIDATION",
		5: "ERROR_CATEGORY_DAEMON",
	}
	ErrorCategory_value = map[string]int32{
		"ERROR_CATEGORY_UNSPECIFIED": 0,
		"ERROR_CATEGORY_SESSION":     1,
		"ERROR_CATEGORY_TERMINAL":    2,
		"ERROR_CATEGORY_TIMEOUT":     3,
		"ERROR_CATEGORY_VALIDATION":  4,
		"ERROR_CATEGORY_DAEMON":      5,
	}
)

func (x ErrorCategory) Enum() *ErrorCategory {
	p := new(ErrorCategory)
	*p = x
	return p
}

func (x ErrorCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_virtui_v1_virtui_proto_enumTypes[1].Descriptor()
}

func (ErrorCategory) Type() protoreflect.EnumType {
	return &file_proto_virtui_v1_virtui_proto_enumTypes[1]
}

func (x ErrorCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCategory.Descriptor instead.
func (ErrorCategory) EnumDescriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{1}
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       []string               `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Env           []string               `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	Dir           string                 `protobuf:"bytes,5,opt,name=dir,proto3" json:"dir,omitempty"`
	Record        bool                   `protobuf:"varint,6,opt,name=record,proto3" json:"record,omitempty"`
	RecordPath    string                 `protobuf:"bytes,7,opt,name=record_path,json=recordPath,proto3" json:"record_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RunRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *RunRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *RunRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RunRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *RunRequest) GetRecord() bool {
	if x != nil {
		return x.Record
	}
	return false
}

func (x *RunRequest) GetRecordPath() string {
	if x != nil {
		return x.RecordPath
	}
	return ""
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	RecordingPath string                 `protobuf:"bytes,3,opt,name=recording_path,json=recordingPath,proto3" json:"recording_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{1}
}

func (x *RunResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *RunResponse) GetRecordingPath() string {
	if x != nil {
		return x.RecordingPath
	}
	return ""
}

type KillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Signal        int32                  `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{2}
}

func (x *KillRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *KillRequest) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

type KillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{3}
}

type SessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // optional: if set, return only this session
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionsRequest) Reset() {
	*x = SessionsRequest{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionsRequest) ProtoMessage() {}

func (x *SessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionsRequest.ProtoReflect.Descriptor instead.
func (*SessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{4}
}

func (x *SessionsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionsResponse) Reset() {
	*x = SessionsResponse{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionsResponse) ProtoMessage() {}

func (x *SessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionsResponse.ProtoReflect.Descriptor instead.
func (*SessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{5}
}

func (x *SessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Command       []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Cols          uint32                 `protobuf:"varint,4,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,5,opt,name=rows,proto3" json:"rows,omitempty"`
	Running       bool                   `protobuf:"varint,6,opt,name=running,proto3" json:"running,omitempty"`
	ExitCode      int32                  `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RecordingPath string                 `protobuf:"bytes,9,opt,name=recording_path,json=recordingPath,proto3" json:"recording_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{6}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SessionInfo) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *SessionInfo) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *SessionInfo) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *SessionInfo) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *SessionInfo) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *SessionInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionInfo) GetRecordingPath() string {
	if x != nil {
		return x.RecordingPath
	}
	return ""
}

type ResizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeRequest) Reset() {
	*x = ResizeRequest{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeRequest) ProtoMessage() {}

func (x *ResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeRequest.ProtoReflect.Descriptor instead.
func (*ResizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{7}
}

func (x *ResizeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResizeRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ResizeRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ResizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeResponse) Reset() {
	*x = ResizeResponse{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeResponse) ProtoMessage() {}

func (x *ResizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeResponse.ProtoReflect.Descriptor instead.
func (*ResizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{8}
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Wait          *WaitCondition         `protobuf:"bytes,3,opt,name=wait,proto3" json:"wait,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{9}
}

func (x *ExecRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ExecRequest) GetWait() *WaitCondition {
	if x != nil {
		return x.Wait
	}
	return nil
}

func (x *ExecRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScreenText    string                 `protobuf:"bytes,1,opt,name=screen_text,json=screenText,proto3" json:"screen_text,omitempty"`
	ScreenHash    string                 `protobuf:"bytes,2,opt,name=screen_hash,json=screenHash,proto3" json:"screen_hash,omitempty"`
	CursorRow     uint32                 `protobuf:"varint,3,opt,name=cursor_row,json=cursorRow,proto3" json:"cursor_row,omitempty"`
	CursorCol     uint32                 `protobuf:"varint,4,opt,name=cursor_col,json=cursorCol,proto3" json:"cursor_col,omitempty"`
	ElapsedMs     int64                  `protobuf:"varint,5,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{10}
}

func (x *ExecResponse) GetScreenText() string {
	if x != nil {
		return x.ScreenText
	}
	return ""
}

func (x *ExecResponse) GetScreenHash() string {
	if x != nil {
		return x.ScreenHash
	}
	return ""
}

func (x *ExecResponse) GetCursorRow() uint32 {
	if x != nil {
		return x.CursorRow
	}
	return 0
}

func (x *ExecResponse) GetCursorCol() uint32 {
	if x != nil {
		return x.CursorCol
	}
	return 0
}

func (x *ExecResponse) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

type ScreenshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NoColor       bool                   `protobuf:"varint,2,opt,name=no_color,json=noColor,proto3" json:"no_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotRequest) Reset() {
	*x = ScreenshotRequest{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotRequest) ProtoMessage() {}

func (x *ScreenshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotRequest.ProtoReflect.Descriptor instead.
func (*ScreenshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{11}
}

func (x *ScreenshotRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ScreenshotRequest) GetNoColor() bool {
	if x != nil {
		return x.NoColor
	}
	return false
}

type ScreenshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScreenText    string                 `protobuf:"bytes,1,opt,name=screen_text,json=screenText,proto3" json:"screen_text,omitempty"`
	ScreenHash    string                 `protobuf:"bytes,2,opt,name=screen_hash,json=screenHash,proto3" json:"screen_hash,omitempty"`
	CursorRow     uint32                 `protobuf:"varint,3,opt,name=cursor_row,json=cursorRow,proto3" json:"cursor_row,omitempty"`
	CursorCol     uint32                 `protobuf:"varint,4,opt,name=cursor_col,json=cursorCol,proto3" json:"cursor_col,omitempty"`
	Cols          uint32                 `protobuf:"varint,5,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,6,opt,name=rows,proto3" json:"rows,omitempty"`
	ScreenAnsi    string                 `protobuf:"bytes,7,opt,name=screen_ansi,json=screenAnsi,proto3" json:"screen_ansi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotResponse) Reset() {
	*x = ScreenshotResponse{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotResponse) ProtoMessage() {}

func (x *ScreenshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotResponse.ProtoReflect.Descriptor instead.
func (*ScreenshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{12}
}

func (x *ScreenshotResponse) GetScreenText() string {
	if x != nil {
		return x.ScreenText
	}
	return ""
}

func (x *ScreenshotResponse) GetScreenHash() string {
	if x != nil {
		return x.ScreenHash
	}
	return ""
}

func (x *ScreenshotResponse) GetCursorRow() uint32 {
	if x != nil {
		return x.CursorRow
	}
	return 0
}

func (x *ScreenshotResponse) GetCursorCol() uint32 {
	if x != nil {
		return x.CursorCol
	}
	return 0
}

func (x *ScreenshotResponse) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ScreenshotResponse) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ScreenshotResponse) GetScreenAnsi() string {
	if x != nil {
		return x.ScreenAnsi
	}
	return ""
}

type PressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Keys          []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Repeat        uint32                 `protobuf:"varint,3,opt,name=repeat,proto3" json:"repeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PressRequest) Reset() {
	*x = PressRequest{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressRequest) ProtoMessage() {}

func (x *PressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressRequest.ProtoReflect.Descriptor instead.
func (*PressRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{13}
}

func (x *PressRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PressRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *PressRequest) GetRepeat() uint32 {
	if x != nil {
		return x.Repeat
	}
	return 0
}

type PressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScreenText    string                 `protobuf:"bytes,1,opt,name=screen_text,json=screenText,proto3" json:"screen_text,omitempty"`
	ScreenHash    string                 `protobuf:"bytes,2,opt,name=screen_hash,json=screenHash,proto3" json:"screen_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PressResponse) Reset() {
	*x = PressResponse{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressResponse) ProtoMessage() {}

func (x *PressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressResponse.ProtoReflect.Descriptor instead.
func (*PressResponse) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{14}
}

func (x *PressResponse) GetScreenText() string {
	if x != nil {
		return x.ScreenText
	}
	return ""
}

func (x *PressResponse) GetScreenHash() string {
	if x != nil {
		return x.ScreenHash
	}
	return ""
}

type TypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeRequest) Reset() {
	*x = TypeRequest{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeRequest) ProtoMessage() {}

func (x *TypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeRequest.ProtoReflect.Descriptor instead.
func (*TypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{15}
}

func (x *TypeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TypeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScreenText    string                 `protobuf:"bytes,1,opt,name=screen_text,json=screenText,proto3" json:"screen_text,omitempty"`
	ScreenHash    string                 `protobuf:"bytes,2,opt,name=screen_hash,json=screenHash,proto3" json:"screen_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeResponse) Reset() {
	*x = TypeResponse{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeResponse) ProtoMessage() {}

func (x *TypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeResponse.ProtoReflect.Descriptor instead.
func (*TypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{16}
}

func (x *TypeResponse) GetScreenText() string {
	if x != nil {
		return x.ScreenText
	}
	return ""
}

func (x *TypeResponse) GetScreenHash() string {
	if x != nil {
		return x.ScreenHash
	}
	return ""
}

type WaitCondition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Condition:
	//
	//	*WaitCondition_Text
	//	*WaitCondition_Stable
	//	*WaitCondition_Gone
	//	*WaitCondition_Regex
	Condition     isWaitCondition_Condition `protobuf_oneof:"condition"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitCondition) Reset() {
	*x = WaitCondition{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitCondition) ProtoMessage() {}

func (x *WaitCondition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitCondition.ProtoReflect.Descriptor instead.
func (*WaitCondition) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{17}
}

func (x *WaitCondition) GetCondition() isWaitCondition_Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *WaitCondition) GetText() string {
	if x != nil {
		if x, ok := x.Condition.(*WaitCondition_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *WaitCondition) GetStable() bool {
	if x != nil {
		if x, ok := x.Condition.(*WaitCondition_Stable); ok {
			return x.Stable
		}
	}
	return false
}

func (x *WaitCondition) GetGone() string {
	if x != nil {
		if x, ok := x.Condition.(*WaitCondition_Gone); ok {
			return x.Gone
		}
	}
	return ""
}

func (x *WaitCondition) GetRegex() string {
	if x != nil {
		if x, ok := x.Condition.(*WaitCondition_Regex); ok {
			return x.Regex
		}
	}
	return ""
}

type isWaitCondition_Condition interface {
	isWaitCondition_Condition()
}

type WaitCondition_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type WaitCondition_Stable struct {
	Stable bool `protobuf:"varint,2,opt,name=stable,proto3,oneof"`
}

type WaitCondition_Gone struct {
	Gone string `protobuf:"bytes,3,opt,name=gone,proto3,oneof"`
}

type WaitCondition_Regex struct {
	Regex string `protobuf:"bytes,4,opt,name=regex,proto3,oneof"`
}

func (*WaitCondition_Text) isWaitCondition_Condition() {}

func (*WaitCondition_Stable) isWaitCondition_Condition() {}

func (*WaitCondition_Gone) isWaitCondition_Condition() {}

func (*WaitCondition_Regex) isWaitCondition_Condition() {}

type WaitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Condition     *WaitCondition         `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitRequest) Reset() {
	*x = WaitRequest{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitRequest) ProtoMessage() {}

func (x *WaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitRequest.ProtoReflect.Descriptor instead.
func (*WaitRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{18}
}

func (x *WaitRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WaitRequest) GetCondition() *WaitCondition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *WaitRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type WaitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScreenText    string                 `protobuf:"bytes,1,opt,name=screen_text,json=screenText,proto3" json:"screen_text,omitempty"`
	ScreenHash    string                 `protobuf:"bytes,2,opt,name=screen_hash,json=screenHash,proto3" json:"screen_hash,omitempty"`
	ElapsedMs     int64                  `protobuf:"varint,3,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitResponse) Reset() {
	*x = WaitResponse{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitResponse) ProtoMessage() {}

func (x *WaitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitResponse.ProtoReflect.Descriptor instead.
func (*WaitResponse) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{19}
}

func (x *WaitResponse) GetScreenText() string {
	if x != nil {
		return x.ScreenText
	}
	return ""
}

func (x *WaitResponse) GetScreenHash() string {
	if x != nil {
		return x.ScreenHash
	}
	return ""
}

func (x *WaitResponse) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

type PipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Steps         []*PipelineStep        `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	StopOnError   bool                   `protobuf:"varint,3,opt,name=stop_on_error,json=stopOnError,proto3" json:"stop_on_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineRequest) Reset() {
	*x = PipelineRequest{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineRequest) ProtoMessage() {}

func (x *PipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineRequest.ProtoReflect.Descriptor instead.
func (*PipelineRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{20}
}

func (x *PipelineRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PipelineRequest) GetSteps() []*PipelineStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *PipelineRequest) GetStopOnError() bool {
	if x != nil {
		return x.StopOnError
	}
	return false
}

type PipelineStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Step:
	//
	//	*PipelineStep_Exec
	//	*PipelineStep_Press
	//	*PipelineStep_Type
	//	*PipelineStep_Wait
	//	*PipelineStep_Screenshot
	//	*PipelineStep_Sleep
	Step          isPipelineStep_Step `protobuf_oneof:"step"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineStep) Reset() {
	*x = PipelineStep{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineStep) ProtoMessage() {}

func (x *PipelineStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineStep.ProtoReflect.Descriptor instead.
func (*PipelineStep) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{21}
}

func (x *PipelineStep) GetStep() isPipelineStep_Step {
	if x != nil {
		return x.Step
	}
	return nil
}

func (x *PipelineStep) GetExec() *ExecRequest {
	if x != nil {
		if x, ok := x.Step.(*PipelineStep_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *PipelineStep) GetPress() *PressRequest {
	if x != nil {
		if x, ok := x.Step.(*PipelineStep_Press); ok {
			return x.Press
		}
	}
	return nil
}

func (x *PipelineStep) GetType() *TypeRequest {
	if x != nil {
		if x, ok := x.Step.(*PipelineStep_Type); ok {
			return x.Type
		}
	}
	return nil
}

func (x *PipelineStep) GetWait() *WaitRequest {
	if x != nil {
		if x, ok := x.Step.(*PipelineStep_Wait); ok {
			return x.Wait
		}
	}
	return nil
}

func (x *PipelineStep) GetScreenshot() *ScreenshotRequest {
	if x != nil {
		if x, ok := x.Step.(*PipelineStep_Screenshot); ok {
			return x.Screenshot
		}
	}
	return nil
}

func (x *PipelineStep) GetSleep() *SleepStep {
	if x != nil {
		if x, ok := x.Step.(*PipelineStep_Sleep); ok {
			return x.Sleep
		}
	}
	return nil
}

type isPipelineStep_Step interface {
	isPipelineStep_Step()
}

type PipelineStep_Exec struct {
	Exec *ExecRequest `protobuf:"bytes,1,opt,name=exec,proto3,oneof"`
}

type PipelineStep_Press struct {
	Press *PressRequest `protobuf:"bytes,2,opt,name=press,proto3,oneof"`
}

type PipelineStep_Type struct {
	Type *TypeRequest `protobuf:"bytes,3,opt,name=type,proto3,oneof"`
}

type PipelineStep_Wait struct {
	Wait *WaitRequest `protobuf:"bytes,4,opt,name=wait,proto3,oneof"`
}

type PipelineStep_Screenshot struct {
	Screenshot *ScreenshotRequest `protobuf:"bytes,5,opt,name=screenshot,proto3,oneof"`
}

type PipelineStep_Sleep struct {
	Sleep *SleepStep `protobuf:"bytes,6,opt,name=sleep,proto3,oneof"`
}

func (*PipelineStep_Exec) isPipelineStep_Step() {}

func (*PipelineStep_Press) isPipelineStep_Step() {}

func (*PipelineStep_Type) isPipelineStep_Step() {}

func (*PipelineStep_Wait) isPipelineStep_Step() {}

func (*PipelineStep_Screenshot) isPipelineStep_Step() {}

func (*PipelineStep_Sleep) isPipelineStep_Step() {}

type SleepStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DurationMs    uint32                 `protobuf:"varint,1,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SleepStep) Reset() {
	*x = SleepStep{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SleepStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepStep) ProtoMessage() {}

func (x *SleepStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepStep.ProtoReflect.Descriptor instead.
func (*SleepStep) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{22}
}

func (x *SleepStep) GetDurationMs() uint32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type PipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PipelineStepResult  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineResponse) Reset() {
	*x = PipelineResponse{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineResponse) ProtoMessage() {}

func (x *PipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineResponse.ProtoReflect.Descriptor instead.
func (*PipelineResponse) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{23}
}

func (x *PipelineResponse) GetResults() []*PipelineStepResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type PipelineStepResult struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	StepIndex    uint32                 `protobuf:"varint,1,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	Success      bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*PipelineStepResult_Exec
	//	*PipelineStepResult_Press
	//	*PipelineStepResult_Type
	//	*PipelineStepResult_Wait
	//	*PipelineStepResult_Screenshot
	Result        isPipelineStepResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineStepResult) Reset() {
	*x = PipelineStepResult{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineStepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineStepResult) ProtoMessage() {}

func (x *PipelineStepResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineStepResult.ProtoReflect.Descriptor instead.
func (*PipelineStepResult) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{24}
}

func (x *PipelineStepResult) GetStepIndex() uint32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *PipelineStepResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PipelineStepResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PipelineStepResult) GetResult() isPipelineStepResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PipelineStepResult) GetExec() *ExecResponse {
	if x != nil {
		if x, ok := x.Result.(*PipelineStepResult_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *PipelineStepResult) GetPress() *PressResponse {
	if x != nil {
		if x, ok := x.Result.(*PipelineStepResult_Press); ok {
			return x.Press
		}
	}
	return nil
}

func (x *PipelineStepResult) GetType() *TypeResponse {
	if x != nil {
		if x, ok := x.Result.(*PipelineStepResult_Type); ok {
			return x.Type
		}
	}
	return nil
}

func (x *PipelineStepResult) GetWait() *WaitResponse {
	if x != nil {
		if x, ok := x.Result.(*PipelineStepResult_Wait); ok {
			return x.Wait
		}
	}
	return nil
}

func (x *PipelineStepResult) GetScreenshot() *ScreenshotResponse {
	if x != nil {
		if x, ok := x.Result.(*PipelineStepResult_Screenshot); ok {
			return x.Screenshot
		}
	}
	return nil
}

type isPipelineStepResult_Result interface {
	isPipelineStepResult_Result()
}

type PipelineStepResult_Exec struct {
	Exec *ExecResponse `protobuf:"bytes,4,opt,name=exec,proto3,oneof"`
}

type PipelineStepResult_Press struct {
	Press *PressResponse `protobuf:"bytes,5,opt,name=press,proto3,oneof"`
}

type PipelineStepResult_Type struct {
	Type *TypeResponse `protobuf:"bytes,6,opt,name=type,proto3,oneof"`
}

type PipelineStepResult_Wait struct {
	Wait *WaitResponse `protobuf:"bytes,7,opt,name=wait,proto3,oneof"`
}

type PipelineStepResult_Screenshot struct {
	Screenshot *ScreenshotResponse `protobuf:"bytes,8,opt,name=screenshot,proto3,oneof"`
}

func (*PipelineStepResult_Exec) isPipelineStepResult_Result() {}

func (*PipelineStepResult_Press) isPipelineStepResult_Result() {}

func (*PipelineStepResult_Type) isPipelineStepResult_Result() {}

func (*PipelineStepResult_Wait) isPipelineStepResult_Result() {}

func (*PipelineStepResult_Screenshot) isPipelineStepResult_Result() {}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{25}
}

func (x *WatchRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type WatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WatchEventType         `protobuf:"varint,1,opt,name=type,proto3,enum=virtui.v1.WatchEventType" json:"type,omitempty"`
	ScreenText    string                 `protobuf:"bytes,2,opt,name=screen_text,json=screenText,proto3" json:"screen_text,omitempty"`
	ScreenHash    string                 `protobuf:"bytes,3,opt,name=screen_hash,json=screenHash,proto3" json:"screen_hash,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{26}
}

func (x *WatchEvent) GetType() WatchEventType {
	if x != nil {
		return x.Type
	}
	return WatchEventType_WATCH_EVENT_TYPE_UNSPECIFIED
}

func (x *WatchEvent) GetScreenText() string {
	if x != nil {
		return x.ScreenText
	}
	return ""
}

func (x *WatchEvent) GetScreenHash() string {
	if x != nil {
		return x.ScreenHash
	}
	return ""
}

func (x *WatchEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{27}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{28}
}

type StructuredError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Category      ErrorCategory          `protobuf:"varint,2,opt,name=category,proto3,enum=virtui.v1.ErrorCategory" json:"category,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Suggestion    string                 `protobuf:"bytes,5,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	Context       map[string]string      `protobuf:"bytes,6,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructuredError) Reset() {
	*x = StructuredError{}
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructuredError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructuredError) ProtoMessage() {}

func (x *StructuredError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtui_v1_virtui_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructuredError.ProtoReflect.Descriptor instead.
func (*StructuredError) Descriptor() ([]byte, []int) {
	return file_proto_virtui_v1_virtui_proto_rawDescGZIP(), []int{29}
}

func (x *StructuredError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StructuredError) GetCategory() ErrorCategory {
	if x != nil {
		return x.Category
	}
	return ErrorCategory_ERROR_CATEGORY_UNSPECIFIED
}

func (x *StructuredError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StructuredError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *StructuredError) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

func (x *StructuredError) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

var File_proto_virtui_v1_virtui_proto protoreflect.FileDescriptor

const file_proto_virtui_v1_virtui_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/virtui/v1/virtui.proto\x12\tvirtui.v1\"\xab\x01\n" +
	"\n" +
	"RunRequest\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\x12\x10\n" +
	"\x03env\x18\x04 \x03(\tR\x03env\x12\x10\n" +
	"\x03dir\x18\x05 \x01(\tR\x03dir\x12\x16\n" +
	"\x06record\x18\x06 \x01(\bR\x06record\x12\x1f\n" +
	"\vrecord_path\x18\a \x01(\tR\n" +
	"recordPath\"e\n" +
	"\vRunResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12%\n" +
	"\x0erecording_path\x18\x03 \x01(\tR\rrecordingPath\"D\n" +
	"\vKillRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\x05R\x06signal\"\x0e\n" +
	"\fKillResponse\"0\n" +
	"\x0fSessionsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"F\n" +
	"\x10SessionsResponse\x122\n" +
	"\bsessions\x18\x01 \x03(\v2\x16.virtui.v1.SessionInfoR\bsessions\"\xfd\x01\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12\x12\n" +
	"\x04cols\x18\x04 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x05 \x01(\rR\x04rows\x12\x18\n" +
	"\arunning\x18\x06 \x01(\bR\arunning\x12\x1b\n" +
	"\texit_code\x18\a \x01(\x05R\bexitCode\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12%\n" +
	"\x0erecording_path\x18\t \x01(\tR\rrecordingPath\"V\n" +
	"\rResizeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\"\x10\n" +
	"\x0eResizeResponse\"\x8f\x01\n" +
	"\vExecRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12,\n" +
	"\x04wait\x18\x03 \x01(\v2\x18.virtui.v1.WaitConditionR\x04wait\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\rR\ttimeoutMs\"\xad\x01\n" +
	"\fExecResponse\x12\x1f\n" +
	"\vscreen_text\x18\x01 \x01(\tR\n" +
	"screenText\x12\x1f\n" +
	"\vscreen_hash\x18\x02 \x01(\tR\n" +
	"screenHash\x12\x1d\n" +
	"\n" +
	"cursor_row\x18\x03 \x01(\rR\tcursorRow\x12\x1d\n" +
	"\n" +
	"cursor_col\x18\x04 \x01(\rR\tcursorCol\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x05 \x01(\x03R\telapsedMs\"M\n" +
	"\x11ScreenshotRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bno_color\x18\x02 \x01(\bR\anoColor\"\xdd\x01\n" +
	"\x12ScreenshotResponse\x12\x1f\n" +
	"\vscreen_text\x18\x01 \x01(\tR\n" +
	"screenText\x12\x1f\n" +
	"\vscreen_hash\x18\x02 \x01(\tR\n" +
	"screenHash\x12\x1d\n" +
	"\n" +
	"cursor_row\x18\x03 \x01(\rR\tcursorRow\x12\x1d\n" +
	"\n" +
	"cursor_col\x18\x04 \x01(\rR\tcursorCol\x12\x12\n" +
	"\x04cols\x18\x05 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x06 \x01(\rR\x04rows\x12\x1f\n" +
	"\vscreen_ansi\x18\a \x01(\tR\n" +
	"screenAnsi\"Y\n" +
	"\fPressRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\x12\x16\n" +
	"\x06repeat\x18\x03 \x01(\rR\x06repeat\"Q\n" +
	"\rPressResponse\x12\x1f\n" +
	"\vscreen_text\x18\x01 \x01(\tR\n" +
	"screenText\x12\x1f\n" +
	"\vscreen_hash\x18\x02 \x01(\tR\n" +
	"screenHash\"@\n" +
	"\vTypeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"P\n" +
	"\fTypeResponse\x12\x1f\n" +
	"\vscreen_text\x18\x01 \x01(\tR\n" +
	"screenText\x12\x1f\n" +
	"\vscreen_hash\x18\x02 \x01(\tR\n" +
	"screenHash\"z\n" +
	"\rWaitCondition\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12\x18\n" +
	"\x06stable\x18\x02 \x01(\bH\x00R\x06stable\x12\x14\n" +
	"\x04gone\x18\x03 \x01(\tH\x00R\x04gone\x12\x16\n" +
	"\x05regex\x18\x04 \x01(\tH\x00R\x05regexB\v\n" +
	"\tcondition\"\x83\x01\n" +
	"\vWaitRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x126\n" +
	"\tcondition\x18\x02 \x01(\v2\x18.virtui.v1.WaitConditionR\tcondition\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\rR\ttimeoutMs\"o\n" +
	"\fWaitResponse\x12\x1f\n" +
	"\vscreen_text\x18\x01 \x01(\tR\n" +
	"screenText\x12\x1f\n" +
	"\vscreen_hash\x18\x02 \x01(\tR\n" +
	"screenHash\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x03 \x01(\x03R\telapsedMs\"\x83\x01\n" +
	"\x0fPipelineRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12-\n" +
	"\x05steps\x18\x02 \x03(\v2\x17.virtui.v1.PipelineStepR\x05steps\x12\"\n" +
	"\rstop_on_error\x18\x03 \x01(\bR\vstopOnError\"\xbf\x02\n" +
	"\fPipelineStep\x12,\n" +
	"\x04exec\x18\x01 \x01(\v2\x16.virtui.v1.ExecRequestH\x00R\x04exec\x12/\n" +
	"\x05press\x18\x02 \x01(\v2\x17.virtui.v1.PressRequestH\x00R\x05press\x12,\n" +
	"\x04type\x18\x03 \x01(\v2\x16.virtui.v1.TypeRequestH\x00R\x04type\x12,\n" +
	"\x04wait\x18\x04 \x01(\v2\x16.virtui.v1.WaitRequestH\x00R\x04wait\x12>\n" +
	"\n" +
	"screenshot\x18\x05 \x01(\v2\x1c.virtui.v1.ScreenshotRequestH\x00R\n" +
	"screenshot\x12,\n" +
	"\x05sleep\x18\x06 \x01(\v2\x14.virtui.v1.SleepStepH\x00R\x05sleepB\x06\n" +
	"\x04step\",\n" +
	"\tSleepStep\x12\x1f\n" +
	"\vduration_ms\x18\x01 \x01(\rR\n" +
	"durationMs\"K\n" +
	"\x10PipelineResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.virtui.v1.PipelineStepResultR\aresults\"\xfc\x02\n" +
	"\x12PipelineStepResult\x12\x1d\n" +
	"\n" +
	"step_index\x18\x01 \x01(\rR\tstepIndex\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12-\n" +
	"\x04exec\x18\x04 \x01(\v2\x17.virtui.v1.ExecResponseH\x00R\x04exec\x120\n" +
	"\x05press\x18\x05 \x01(\v2\x18.virtui.v1.PressResponseH\x00R\x05press\x12-\n" +
	"\x04type\x18\x06 \x01(\v2\x17.virtui.v1.TypeResponseH\x00R\x04type\x12-\n" +
	"\x04wait\x18\a \x01(\v2\x17.virtui.v1.WaitResponseH\x00R\x04wait\x12?\n" +
	"\n" +
	"screenshot\x18\b \x01(\v2\x1d.virtui.v1.ScreenshotResponseH\x00R\n" +
	"screenshotB\b\n" +
	"\x06result\"-\n" +
	"\fWatchRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x9a\x01\n" +
	"\n" +
	"WatchEvent\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.virtui.v1.WatchEventTypeR\x04type\x12\x1f\n" +
	"\vscreen_text\x18\x02 \x01(\tR\n" +
	"screenText\x12\x1f\n" +
	"\vscreen_hash\x18\x03 \x01(\tR\n" +
	"screenHash\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\xb2\x02\n" +
	"\x0fStructuredError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x124\n" +
	"\bcategory\x18\x02 \x01(\x0e2\x18.virtui.v1.ErrorCategoryR\bcategory\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x05 \x01(\tR\n" +
	"suggestion\x12A\n" +
	"\acontext\x18\x06 \x03(\v2'.virtui.v1.StructuredError.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*t\n" +
	"\x0eWatchEventType\x12 \n" +
	"\x1cWATCH_EVENT_TYPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fWATCH_EVENT_TYPE_SCREEN_CHANGED\x10\x01\x12\x1b\n" +
	"\x17WATCH_EVENT_TYPE_EXITED\x10\x02*\xbe\x01\n" +
	"\rErrorCategory\x12\x1e\n" +
	"\x1aERROR_CATEGORY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ERROR_CATEGORY_SESSION\x10\x01\x12\x1b\n" +
	"\x17ERROR_CATEGORY_TERMINAL\x10\x02\x12\x1a\n" +
	"\x16ERROR_CATEGORY_TIMEOUT\x10\x03\x12\x1d\n" +
	"\x19ERROR_CATEGORY_VALIDATION\x10\x04\x12\x19\n" +
	"\x15ERROR_CATEGORY_DAEMON\x10\x052\xf9\x05\n" +
	"\rVirtuiService\x124\n" +
	"\x03Run\x12\x15.virtui.v1.RunRequest\x1a\x16.virtui.v1.RunResponse\x127\n" +
	"\x04Kill\x12\x16.virtui.v1.KillRequest\x1a\x17.virtui.v1.KillResponse\x12C\n" +
	"\bSessions\x12\x1a.virtui.v1.SessionsRequest\x1a\x1b.virtui.v1.SessionsResponse\x12=\n" +
	"\x06Resize\x12\x18.virtui.v1.ResizeRequest\x1a\x19.virtui.v1.ResizeResponse\x127\n" +
	"\x04Exec\x12\x16.virtui.v1.ExecRequest\x1a\x17.virtui.v1.ExecResponse\x12I\n" +
	"\n" +
	"Screenshot\x12\x1c.virtui.v1.ScreenshotRequest\x1a\x1d.virtui.v1.ScreenshotResponse\x12:\n" +
	"\x05Press\x12\x17.virtui.v1.PressRequest\x1a\x18.virtui.v1.PressResponse\x127\n" +
	"\x04Type\x12\x16.virtui.v1.TypeRequest\x1a\x17.virtui.v1.TypeResponse\x127\n" +
	"\x04Wait\x12\x16.virtui.v1.WaitRequest\x1a\x17.virtui.v1.WaitResponse\x12C\n" +
	"\bPipeline\x12\x1a.virtui.v1.PipelineRequest\x1a\x1b.virtui.v1.PipelineResponse\x129\n" +
	"\x05Watch\x12\x17.virtui.v1.WatchRequest\x1a\x15.virtui.v1.WatchEvent0\x01\x12C\n" +
	"\bShutdown\x12\x1a.virtui.v1.ShutdownRequest\x1a\x1b.virtui.v1.ShutdownResponseB<Z:github.com/honeybadge-labs/virtui/proto/virtui/v1;virtuipbb\x06proto3"

var (
	file_proto_virtui_v1_virtui_proto_rawDescOnce sync.Once
	file_proto_virtui_v1_virtui_proto_rawDescData []byte
)

func file_proto_virtui_v1_virtui_proto_rawDescGZIP() []byte {
	file_proto_virtui_v1_virtui_proto_rawDescOnce.Do(func() {
		file_proto_virtui_v1_virtui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_virtui_v1_virtui_proto_rawDesc), len(file_proto_virtui_v1_virtui_proto_rawDesc)))
	})
	return file_proto_virtui_v1_virtui_proto_rawDescData
}

var file_proto_virtui_v1_virtui_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_virtui_v1_virtui_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_proto_virtui_v1_virtui_proto_goTypes = []any{
	(WatchEventType)(0),        // 0: virtui.v1.WatchEventType
	(ErrorCategory)(0),         // 1: virtui.v1.ErrorCategory
	(*RunRequest)(nil),         // 2: virtui.v1.RunRequest
	(*RunResponse)(nil),        // 3: virtui.v1.RunResponse
	(*KillRequest)(nil),        // 4: virtui.v1.KillRequest
	(*KillResponse)(nil),       // 5: virtui.v1.KillResponse
	(*SessionsRequest)(nil),    // 6: virtui.v1.SessionsRequest
	(*SessionsResponse)(nil),   // 7: virtui.v1.SessionsResponse
	(*SessionInfo)(nil),        // 8: virtui.v1.SessionInfo
	(*ResizeRequest)(nil),      // 9: virtui.v1.ResizeRequest
	(*ResizeResponse)(nil),     // 10: virtui.v1.ResizeResponse
	(*ExecRequest)(nil),        // 11: virtui.v1.ExecRequest
	(*ExecResponse)(nil),       // 12: virtui.v1.ExecResponse
	(*ScreenshotRequest)(nil),  // 13: virtui.v1.ScreenshotRequest
	(*ScreenshotResponse)(nil), // 14: virtui.v1.ScreenshotResponse
	(*PressRequest)(nil),       // 15: virtui.v1.PressRequest
	(*PressResponse)(nil),      // 16: virtui.v1.PressResponse
	(*TypeRequest)(nil),        // 17: virtui.v1.TypeRequest
	(*TypeResponse)(nil),       // 18: virtui.v1.TypeResponse
	(*WaitCondition)(nil),      // 19: virtui.v1.WaitCondition
	(*WaitRequest)(nil),        // 20: virtui.v1.WaitRequest
	(*WaitResponse)(nil),       // 21: virtui.v1.WaitResponse
	(*PipelineRequest)(nil),    // 22: virtui.v1.PipelineRequest
	(*PipelineStep)(nil),       // 23: virtui.v1.PipelineStep
	(*SleepStep)(nil),          // 24: virtui.v1.SleepStep
	(*PipelineResponse)(nil),   // 25: virtui.v1.PipelineResponse
	(*PipelineStepResult)(nil), // 26: virtui.v1.PipelineStepResult
	(*WatchRequest)(nil),       // 27: virtui.v1.WatchRequest
	(*WatchEvent)(nil),         // 28: virtui.v1.WatchEvent
	(*ShutdownRequest)(nil),    // 29: virtui.v1.ShutdownRequest
	(*ShutdownResponse)(nil),   // 30: virtui.v1.ShutdownResponse
	(*StructuredError)(nil),    // 31: virtui.v1.StructuredError
	nil,                        // 32: virtui.v1.StructuredError.ContextEntry
}
var file_proto_virtui_v1_virtui_proto_depIdxs = []int32{
	8,  // 0: virtui.v1.SessionsResponse.sessions:type_name -> virtui.v1.SessionInfo
	19, // 1: virtui.v1.ExecRequest.wait:type_name -> virtui.v1.WaitCondition
	19, // 2: virtui.v1.WaitRequest.condition:type_name -> virtui.v1.WaitCondition
	23, // 3: virtui.v1.PipelineRequest.steps:type_name -> virtui.v1.PipelineStep
	11, // 4: virtui.v1.PipelineStep.exec:type_name -> virtui.v1.ExecRequest
	15, // 5: virtui.v1.PipelineStep.press:type_name -> virtui.v1.PressRequest
	17, // 6: virtui.v1.PipelineStep.type:type_name -> virtui.v1.TypeRequest
	20, // 7: virtui.v1.PipelineStep.wait:type_name -> virtui.v1.WaitRequest
	13, // 8: virtui.v1.PipelineStep.screenshot:type_name -> virtui.v1.ScreenshotRequest
	24, // 9: virtui.v1.PipelineStep.sleep:type_name -> virtui.v1.SleepStep
	26, // 10: virtui.v1.PipelineResponse.results:type_name -> virtui.v1.PipelineStepResult
	12, // 11: virtui.v1.PipelineStepResult.exec:type_name -> virtui.v1.ExecResponse
	16, // 12: virtui.v1.PipelineStepResult.press:type_name -> virtui.v1.PressResponse
	18, // 13: virtui.v1.PipelineStepResult.type:type_name -> virtui.v1.TypeResponse
	21, // 14: virtui.v1.PipelineStepResult.wait:type_name -> virtui.v1.WaitResponse
	14, // 15: virtui.v1.PipelineStepResult.screenshot:type_name -> virtui.v1.ScreenshotResponse
	0,  // 16: virtui.v1.WatchEvent.type:type_name -> virtui.v1.WatchEventType
	1,  // 17: virtui.v1.StructuredError.category:type_name -> virtui.v1.ErrorCategory
	32, // 18: virtui.v1.StructuredError.context:type_name -> virtui.v1.StructuredError.ContextEntry
	2,  // 19: virtui.v1.VirtuiService.Run:input_type -> virtui.v1.RunRequest
	4,  // 20: virtui.v1.VirtuiService.Kill:input_type -> virtui.v1.KillRequest
	6,  // 21: virtui.v1.VirtuiService.Sessions:input_type -> virtui.v1.SessionsRequest
	9,  // 22: virtui.v1.VirtuiService.Resize:input_type -> virtui.v1.ResizeRequest
	11, // 23: virtui.v1.VirtuiService.Exec:input_type -> virtui.v1.ExecRequest
	13, // 24: virtui.v1.VirtuiService.Screenshot:input_type -> virtui.v1.ScreenshotRequest
	15, // 25: virtui.v1.VirtuiService.Press:input_type -> virtui.v1.PressRequest
	17, // 26: virtui.v1.VirtuiService.Type:input_type -> virtui.v1.TypeRequest
	20, // 27: virtui.v1.VirtuiService.Wait:input_type -> virtui.v1.WaitRequest
	22, // 28: virtui.v1.VirtuiService.Pipeline:input_type -> virtui.v1.PipelineRequest
	27, // 29: virtui.v1.VirtuiService.Watch:input_type -> virtui.v1.WatchRequest
	29, // 30: virtui.v1.VirtuiService.Shutdown:input_type -> virtui.v1.ShutdownRequest
	3,  // 31: virtui.v1.VirtuiService.Run:output_type -> virtui.v1.RunResponse
	5,  // 32: virtui.v1.VirtuiService.Kill:output_type -> virtui.v1.KillResponse
	7,  // 33: virtui.v1.VirtuiService.Sessions:output_type -> virtui.v1.SessionsResponse
	10, // 34: virtui.v1.VirtuiService.Resize:output_type -> virtui.v1.ResizeResponse
	12, // 35: virtui.v1.VirtuiService.Exec:output_type -> virtui.v1.ExecResponse
	14, // 36: virtui.v1.VirtuiService.Screenshot:output_type -> virtui.v1.ScreenshotResponse
	16, // 37: virtui.v1.VirtuiService.Press:output_type -> virtui.v1.PressResponse
	18, // 38: virtui.v1.VirtuiService.Type:output_type -> virtui.v1.TypeResponse
	21, // 39: virtui.v1.VirtuiService.Wait:output_type -> virtui.v1.WaitResponse
	25, // 40: virtui.v1.VirtuiService.Pipeline:output_type -> virtui.v1.PipelineResponse
	28, // 41: virtui.v1.VirtuiService.Watch:output_type -> virtui.v1.WatchEvent
	30, // 42: virtui.v1.VirtuiService.Shutdown:output_type -> virtui.v1.ShutdownResponse
	31, // [31:43] is the sub-list for method output_type
	19, // [19:31] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_virtui_v1_virtui_proto_init() }
func file_proto_virtui_v1_virtui_proto_init() {
	if File_proto_virtui_v1_virtui_proto != nil {
		return
	}
	file_proto_virtui_v1_virtui_proto_msgTypes[17].OneofWrappers = []any{
		(*WaitCondition_Text)(nil),
		(*WaitCondition_Stable)(nil),
		(*WaitCondition_Gone)(nil),
		(*WaitCondition_Regex)(nil),
	}
	file_proto_virtui_v1_virtui_proto_msgTypes[21].OneofWrappers = []any{
		(*PipelineStep_Exec)(nil),
		(*PipelineStep_Press)(nil),
		(*PipelineStep_Type)(nil),
		(*PipelineStep_Wait)(nil),
		(*PipelineStep_Screenshot)(nil),
		(*PipelineStep_Sleep)(nil),
	}
	file_proto_virtui_v1_virtui_proto_msgTypes[24].OneofWrappers = []any{
		(*PipelineStepResult_Exec)(nil),
		(*PipelineStepResult_Press)(nil),
		(*PipelineStepResult_Type)(nil),
		(*PipelineStepResult_Wait)(nil),
		(*PipelineStepResult_Screenshot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_virtui_v1_virtui_proto_rawDesc), len(file_proto_virtui_v1_virtui_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_virtui_v1_virtui_proto_goTypes,
		DependencyIndexes: file_proto_virtui_v1_virtui_proto_depIdxs,
		EnumInfos:         file_proto_virtui_v1_virtui_proto_enumTypes,
		MessageInfos:      file_proto_virtui_v1_virtui_proto_msgTypes,
	}.Build()
	File_proto_virtui_v1_virtui_proto = out.File
	file_proto_virtui_v1_virtui_proto_goTypes = nil
	file_proto_virtui_v1_virtui_proto_depIdxs = nil
}
