// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/virtui/v1/virtui.proto

package virtuipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VirtuiService_Run_FullMethodName        = "/virtui.v1.VirtuiService/Run"
	VirtuiService_Kill_FullMethodName       = "/virtui.v1.VirtuiService/Kill"
	VirtuiService_Sessions_FullMethodName   = "/virtui.v1.VirtuiService/Sessions"
	VirtuiService_Resize_FullMethodName     = "/virtui.v1.VirtuiService/Resize"
	VirtuiService_Exec_FullMethodName       = "/virtui.v1.VirtuiService/Exec"
	VirtuiService_Screenshot_FullMethodName = "/virtui.v1.VirtuiService/Screenshot"
	VirtuiService_Press_FullMethodName      = "/virtui.v1.VirtuiService/Press"
	VirtuiService_Type_FullMethodName       = "/virtui.v1.VirtuiService/Type"
	VirtuiService_Wait_FullMethodName       = "/virtui.v1.VirtuiService/Wait"
	VirtuiService_Pipeline_FullMethodName   = "/virtui.v1.VirtuiService/Pipeline"
	VirtuiService_Watch_FullMethodName      = "/virtui.v1.VirtuiService/Watch"
)

// VirtuiServiceClient is the client API for VirtuiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VirtuiServiceClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error)
	Sessions(ctx context.Context, in *SessionsRequest, opts ...grpc.CallOption) (*SessionsResponse, error)
	Resize(ctx context.Context, in *ResizeRequest, opts ...grpc.CallOption) (*ResizeResponse, error)
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	Screenshot(ctx context.Context, in *ScreenshotRequest, opts ...grpc.CallOption) (*ScreenshotResponse, error)
	Press(ctx context.Context, in *PressRequest, opts ...grpc.CallOption) (*PressResponse, error)
	Type(ctx context.Context, in *TypeRequest, opts ...grpc.CallOption) (*TypeResponse, error)
	Wait(ctx context.Context, in *WaitRequest, opts ...grpc.CallOption) (*WaitResponse, error)
	Pipeline(ctx context.Context, in *PipelineRequest, opts ...grpc.CallOption) (*PipelineResponse, error)
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
}

type virtuiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVirtuiServiceClient(cc grpc.ClientConnInterface) VirtuiServiceClient {
	return &virtuiServiceClient{cc}
}

func (c *virtuiServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, VirtuiService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtuiServiceClient) Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillResponse)
	err := c.cc.Invoke(ctx, VirtuiService_Kill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtuiServiceClient) Sessions(ctx context.Context, in *SessionsRequest, opts ...grpc.CallOption) (*SessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionsResponse)
	err := c.cc.Invoke(ctx, VirtuiService_Sessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtuiServiceClient) Resize(ctx context.Context, in *ResizeRequest, opts ...grpc.CallOption) (*ResizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResizeResponse)
	err := c.cc.Invoke(ctx, VirtuiService_Resize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtuiServiceClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, VirtuiService_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtuiServiceClient) Screenshot(ctx context.Context, in *ScreenshotRequest, opts ...grpc.CallOption) (*ScreenshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScreenshotResponse)
	err := c.cc.Invoke(ctx, VirtuiService_Screenshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtuiServiceClient) Press(ctx context.Context, in *PressRequest, opts ...grpc.CallOption) (*PressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PressResponse)
	err := c.cc.Invoke(ctx, VirtuiService_Press_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtuiServiceClient) Type(ctx context.Context, in *TypeRequest, opts ...grpc.CallOption) (*TypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypeResponse)
	err := c.cc.Invoke(ctx, VirtuiService_Type_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtuiServiceClient) Wait(ctx context.Context, in *WaitRequest, opts ...grpc.CallOption) (*WaitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitResponse)
	err := c.cc.Invoke(ctx, VirtuiService_Wait_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtuiServiceClient) Pipeline(ctx context.Context, in *PipelineRequest, opts ...grpc.CallOption) (*PipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PipelineResponse)
	err := c.cc.Invoke(ctx, VirtuiService_Pipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtuiServiceClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VirtuiService_ServiceDesc.Streams[0], VirtuiService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VirtuiService_WatchClient = grpc.ServerStreamingClient[WatchEvent]

// VirtuiServiceServer is the server API for VirtuiService service.
// All implementations must embed UnimplementedVirtuiServiceServer
// for forward compatibility.
type VirtuiServiceServer interface {
	Run(context.Context, *RunRequest) (*RunResponse, error)
	Kill(context.Context, *KillRequest) (*KillResponse, error)
	Sessions(context.Context, *SessionsRequest) (*SessionsResponse, error)
	Resize(context.Context, *ResizeRequest) (*ResizeResponse, error)
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	Screenshot(context.Context, *ScreenshotRequest) (*ScreenshotResponse, error)
	Press(context.Context, *PressRequest) (*PressResponse, error)
	Type(context.Context, *TypeRequest) (*TypeResponse, error)
	Wait(context.Context, *WaitRequest) (*WaitResponse, error)
	Pipeline(context.Context, *PipelineRequest) (*PipelineResponse, error)
	Watch(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	mustEmbedUnimplementedVirtuiServiceServer()
}

// UnimplementedVirtuiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVirtuiServiceServer struct{}

func (UnimplementedVirtuiServiceServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedVirtuiServiceServer) Kill(context.Context, *KillRequest) (*KillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Kill not implemented")
}
func (UnimplementedVirtuiServiceServer) Sessions(context.Context, *SessionsRequest) (*SessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sessions not implemented")
}
func (UnimplementedVirtuiServiceServer) Resize(context.Context, *ResizeRequest) (*ResizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resize not implemented")
}
func (UnimplementedVirtuiServiceServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedVirtuiServiceServer) Screenshot(context.Context, *ScreenshotRequest) (*ScreenshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Screenshot not implemented")
}
func (UnimplementedVirtuiServiceServer) Press(context.Context, *PressRequest) (*PressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Press not implemented")
}
func (UnimplementedVirtuiServiceServer) Type(context.Context, *TypeRequest) (*TypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Type not implemented")
}
func (UnimplementedVirtuiServiceServer) Wait(context.Context, *WaitRequest) (*WaitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Wait not implemented")
}
func (UnimplementedVirtuiServiceServer) Pipeline(context.Context, *PipelineRequest) (*PipelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pipeline not implemented")
}
func (UnimplementedVirtuiServiceServer) Watch(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedVirtuiServiceServer) mustEmbedUnimplementedVirtuiServiceServer() {}
func (UnimplementedVirtuiServiceServer) testEmbeddedByValue()                       {}

// UnsafeVirtuiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VirtuiServiceServer will
// result in compilation errors.
type UnsafeVirtuiServiceServer interface {
	mustEmbedUnimplementedVirtuiServiceServer()
}

func RegisterVirtuiServiceServer(s grpc.ServiceRegistrar, srv VirtuiServiceServer) {
	// If the following call panics, it indicates UnimplementedVirtuiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VirtuiService_ServiceDesc, srv)
}

func _VirtuiService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtuiServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtuiService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtuiServiceServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtuiService_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtuiServiceServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtuiService_Kill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtuiServiceServer).Kill(ctx, req.(*KillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtuiService_Sessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtuiServiceServer).Sessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtuiService_Sessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtuiServiceServer).Sessions(ctx, req.(*SessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtuiService_Resize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtuiServiceServer).Resize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtuiService_Resize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtuiServiceServer).Resize(ctx, req.(*ResizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtuiService_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtuiServiceServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtuiService_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtuiServiceServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtuiService_Screenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtuiServiceServer).Screenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtuiService_Screenshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtuiServiceServer).Screenshot(ctx, req.(*ScreenshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtuiService_Press_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtuiServiceServer).Press(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtuiService_Press_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtuiServiceServer).Press(ctx, req.(*PressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtuiService_Type_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtuiServiceServer).Type(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtuiService_Type_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtuiServiceServer).Type(ctx, req.(*TypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtuiService_Wait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtuiServiceServer).Wait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtuiService_Wait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtuiServiceServer).Wait(ctx, req.(*WaitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtuiService_Pipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtuiServiceServer).Pipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtuiService_Pipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtuiServiceServer).Pipeline(ctx, req.(*PipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtuiService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VirtuiServiceServer).Watch(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VirtuiService_WatchServer = grpc.ServerStreamingServer[WatchEvent]

// VirtuiService_ServiceDesc is the grpc.ServiceDesc for VirtuiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VirtuiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "virtui.v1.VirtuiService",
	HandlerType: (*VirtuiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _VirtuiService_Run_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _VirtuiService_Kill_Handler,
		},
		{
			MethodName: "Sessions",
			Handler:    _VirtuiService_Sessions_Handler,
		},
		{
			MethodName: "Resize",
			Handler:    _VirtuiService_Resize_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _VirtuiService_Exec_Handler,
		},
		{
			MethodName: "Screenshot",
			Handler:    _VirtuiService_Screenshot_Handler,
		},
		{
			MethodName: "Press",
			Handler:    _VirtuiService_Press_Handler,
		},
		{
			MethodName: "Type",
			Handler:    _VirtuiService_Type_Handler,
		},
		{
			MethodName: "Wait",
			Handler:    _VirtuiService_Wait_Handler,
		},
		{
			MethodName: "Pipeline",
			Handler:    _VirtuiService_Pipeline_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _VirtuiService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/virtui/v1/virtui.proto",
}
